---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      name: cronjobdata
    spec:
      backoffLimit: 3
      template:
        metadata:
          name: cronjobpod
          labels:
            purpose: execute
        spec:
          restartPolicy: OnFailure
          containers:
            - name: download
              image: alpine:3
              command:
                - sleep
                - 30s