---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-congigmap
      image: mysql:8
      envFrom:
        -configMapRef:
          name: mysql-congigmap
          optional: false
      ports:
        - containerPort: 3306