---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nop-deploy
  labels:
    app: nopcommerce
spec: 
  minReadySeconds: 1
  replicas: 2
  selector: 
    matchLabels: 
      app: nopcommerce
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate  
  template:
    metadata:
      name: nop-pod
      labels:
        app: nopcommerce
    spec:
      containers:
        - name: nopcommerce
          image: prakashreddy2525/nopcommerce
          ports:
            - containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 5000
          livenessProbe:
            tcpSocket:
              port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nop-svc
  labels:
    app: nopcommerce
spec:
  selector:
    app: nopcommerce
  type: LoadBalancer
  ports:
    - name: webport
      port: 32000
      protocol: TCP
      targetPort: 5000